name: Deploy Blazor WASM to GitHub Pages

on:
    push:
        branches: [master]

jobs:
    deploy-to-github-pages:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2

        - name: Setup .NET Core SDK
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '9.0.x'

        - name: Publish .NET Project
          run: dotnet publish ./XboxTrack/XboxTrack.csproj -c Release -o release --nologo
        
        - name: Rewrite base href
          uses: SteveSandersonMS/ghaction-rewrite-base-href@v1.1.0
          with:
            html_path: release/wwwroot/index.html
            base_href: /XboxTrack/    
        
        - name: copy index.html to 404.html
          run: cp release/wwwroot/index.html release/wwwroot/404.html

        - name: Add .nojekyll file
          run: touch release/wwwroot/.nojekyll

        - name: Commit wwwroot to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: gh-pages
            publish_dir: ./release/wwwroot
